name: Psychics
main: io.github.monun.psychics.plugin.PsychicsPlugin
api-version: '1.20'
version: $version
author: Monun
libraries:
  - io.github.monun:tap-core:4.9.6
  - io.github.monun:invfx-core:3.3.0
  - io.github.monun:kommand-core:3.1.6
